### PR TITLE
#225 Refactor App-test.js

### PR DESCRIPTION
**Pull request by Archaeologist03**
#225
Refactoring to arrow functions and vars to consts.

### CODE REVIEW

**Comment by AlexLakatos** [comment]
this looks really good. Could you refactor the rest of the tests as well please?

**Comment by AlexLakatos** [comment]
It also looks like the tests are failing cause of prettier, could you fix that as well please?
```
/Users/travis/build/Nexmo/nexmo-node/test/App-test.js
  17:43  error  Insert `⏎···`  prettier/prettier
  18:1   error  Delete `····`  prettier/prettier
  19:78  error  Insert `⏎···`  prettier/prettier
  51:6   error  Delete `·`     prettier/prettier
```

**Comment by Archaeologist03** [comment]
Yeah sure, I will try to do them all.
By the way prettier is just another thing for formating code, any formating exstension would do the job?

**Comment by AlexLakatos** [comment]
You'll have to use the prettier rules we use in the repo to make that pass in the CI

**Comment by robincher** [comment]
Maybe you need to modify the eslint config too.

**Pull request closed without merging**
