### PR TITLE
build: updated dependencies

### PR DESCRIPTION
**Pull request by manchuck**
Removed unused dependencies and fixed the scripts for the child packages

### CODE REVIEW

**Comment by manchuck** [comment]
requires #727

**Review by dragonmantank — CHANGES_REQUESTED** [review]
Was this based on an older branch? All the packages split out `auth`, `server-client`, and `vetch`, but those should be all wrapped up in a single dependency of `server-client`. A lot of them are also updating from `server-client:1.0.0` to `1.0.1`, which already happened in the main 3.x branch.

**Comment by manchuck** [comment]
@dragonmantank This was based on the `3.x` branch. I used a tool called [depcheck](https://www.npmjs.com/package/depcheck) on each of the packages to ensure that we have the correct dependencies when installing the packages on their own (`lerna exec --no-bail --prefix --stream npx depcheck`). It checks the import/require statements to ensure that the package.json is not missing anything.

**Comment by manchuck** [comment]
This technically requires both #727 and #728 as those clean up the linter and typescript configs. Although this should not impact development on its own

**Pull request closed without merging**
