### PR TITLE
added typings for the beta channel API

### PR DESCRIPTION
**Pull request by crutchcorn**
This is an early version of the typings for the Channel API (which is currently in beta). The documentation I referenced for the typings live here:

https://developer.nexmo.com/api/messages-olympus 

Line 193 of the `index.d.ts` file does leave a comment of a difference between the documentation and code implementation that I noticed while working on the typings.

This should not introduce any breaking changes over the previous beta.

### CODE REVIEW

**Comment by crutchcorn** [comment]
I'll be removing the BasicAuth typings per #300

**Comment by crutchcorn** [comment]
BasicAuth typings have now been removed. Should be ready for review

**Comment by crutchcorn** [comment]
The Codecov is innacurate. I accidently pushed changes to both of those files, then reverted and force pushed to remove those changes

**Comment by kellyjandrews** [comment]
I'm going to get something in place for the GA version, and then I'll swing back and pick this one up.  Thanks for your patience!

**Comment by crutchcorn** [comment]
Apologies for the ping, but I wanted to check on the status of this PR.

@kellyjandrews, if I fix the merge conflict, would this PR go good-to-go?

**Comment by kellyjandrews** [comment]
@crutchcorn I think that would be great - I have a few items to get through this week for the beta version, and can incorporate these in the next update.

**Comment by crutchcorn** [comment]
@kellyjandrews I've updated the PR to fix merge conflicts. Did an initial glance back at the docs to see if any of the API has changed dramatically, and it seems like the typings are still up-to-date and relevant. Assuming no other change requests, this should be good-to-merge

**Comment by kellyjandrews** [comment]
Thanks @crutchcorn - I'll get it reviewed and released first thing next week.

**Comment by crutchcorn** [comment]
@kellyjandrews just wanted to check if this was good-to-merge

**Review by kellyjandrews — APPROVED** [review]

**Comment by kellyjandrews** [comment]
Sorry for the delay on my end. I'll get a new version pushed out.

**Comment by kellyjandrews** [comment]
@crutchcorn - should be a new beta version available on npm. Sorry for the delay!

**Comment by crutchcorn** [comment]
No worries @kellyjandrews - I appreciate you pushing this over the finish line! 🚀

**Pull request merged**
