### PR TITLE
Update year in LICENSE.txt

### LINKED ISSUE #208: Update year in license
Currently, the year in license is 2016.
Would be great if we could change it to 2016-present as this would avoid copyright issues in the future.

### PR DESCRIPTION
**Pull request by rahulkumaran**
Fixes #208 
The year has been updated to 2016-present
This is a one time change and need not be changed every year. This will also ensure no copyright issues arise in the future.
Please do review.
Thanks!

### CODE REVIEW

**Comment by AlexLakatos** [comment]
The MIT license is not flexible enough to allow perpetuity. Current year needs to be used. Can you update that to say 2018 please?

**Comment by rahulkumaran** [comment]
Done @AlexLakatos

**Comment by AlexLakatos** [comment]
Thank you! Can I ask you do that for other repos as well in http://github.com/nexmo-community, pease?

**Comment by rahulkumaran** [comment]
@AlexLakatos in all the 107 repositories? Would it be possible to get a collaborator access to directly push changes into the LICENSE file? Because otherwise I'll have to fork each of them right?

**Pull request merged**
