### PR TITLE
Fixed Shallow Copy 

### PR DESCRIPTION
**Pull request by ashoksahoo**
Fixed issue #16 by changing shallow copy to deep copy.

### CODE REVIEW

**Comment by isabo** [comment]
IMHO a more intuitive explanation is: "Modify a private copy of msgPath instead of the original, which should be treated as a constant."

i.e. the original code does not do a shallow copy -- it doesn't copy the object at all!

**Comment by pvela** [comment]
Thanks for pointing out the problem and the pull request.

**Comment by ashoksahoo** [comment]
It will get updated to npm automatically or it takes a while?

**Comment by pvela** [comment]
Its updated in NPM now. This issue existed in other functions as well, fixed all of them. Thanks again.

**Pull request merged**
