### PR TITLE
Implement send via US shortcodes

### PR DESCRIPTION
**Pull request by backhand**
Quick implementation US shortcodes. I've tried to follow the overall style of the library and what code conventions I could see.

### CODE REVIEW

**Comment by pvela** [comment]
Hi,

Thanks for the PR. The code convention looks good. Were you able to test this by using your shortcodes?

**Comment by backhand** [comment]
Yes, I've tested it with an alert shortcode, and it works. The other two, 2FA and marketing, follows the same calling signature so I have no reason to believe they won't work.

**Comment by backhand** [comment]
Are you going to merge this? If not, please tell me if you've found a problem.

**Comment by pvela** [comment]
Its merged and published to npm. Thank you for the contribution.

**Comment by backhand** [comment]
Thanks, and you're welcome.

**Pull request merged**
