### PR TITLE
bump dependencies

### PR DESCRIPTION
**Pull request by knoxcard**
these dependencies are older than my underwear

### CODE REVIEW

**Comment by AlexLakatos** [comment]
Travis is erroring because the lock file is not updated. Can you please update that as well?
```
npm ERR! cipm can only install packages when your package.json and package-lock.json or npm-shrinkwrap.json are in sync. Please update your lock file with `npm install` before continuing.
npm ERR! 
npm ERR! 
npm ERR! Invalid: lock file's jsonwebtoken@8.2.1 does not satisfy jsonwebtoken@^8.3.0
npm ERR! Invalid: lock file's request@2.85.0 does not satisfy request@^2.88.0
npm ERR! Invalid: lock file's uuid@2.0.3 does not satisfy uuid@^3.3.2
```

**Comment by knoxcard** [comment]
Don't know how to do it, tried cloning the repo locally then...
git add .
git commit -am "update dependencies"
git push origin master
user: ********
pass: ********

Username for 'https://github.com': knoxcard
Password for 'https://knoxcard@github.com':
remote: Permission to Nexmo/nexmo-node.git denied to knoxcard.
fatal: unable to access 'https://github.com/Nexmo/nexmo-node.git/': The requested URL returned error: 403

**Comment by AlexLakatos** [comment]
You can't push directly to master. You'll have to fork or push to the knoxcard:patch-1 branch in your fork. That'll update this PR automatically.

**Comment by knoxcard** [comment]
Gotchya, I'll try to get around to this today or tomorrow.

**Comment by lornajane** [comment]
Closing due to inactivity

**Pull request closed without merging**
