### PR TITLE
Allow for Full URL Overrides in Constructor

### PR DESCRIPTION
**Pull request by drph4nt0m**
# Description

Added regex check to allow for Full URL Overrides in Constructor and if it doesn't match the regex, prefix it with https:// protocol.

## Motivation and Context

#377 

## Testing Details

No tests should be affected. Have tried a few examples locally.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by drph4nt0m** [comment]
Ohh I think my local linter settings didn't match with the repo linter. Do you want me to push the code with the linter fix?

**Comment by kellyjandrews** [comment]
Yes @drph4nt0m - all tests should be passing.  If you could get that fixed up, should be all good. Thanks for your contribution!

**Comment by drph4nt0m** [comment]
I forgot about the `npm run lint-fix` and was trying to fix lint issues manually. 🤦 

All checks passes now.

@kellyjandrews do check now.

**Comment by drph4nt0m** [comment]
Hey @kellyjandrews any update?

**Comment by kellyjandrews** [comment]
@drph4nt0m Working through the backlog over the next couple of days - you get credit for the PR regardless - so all good.  Thanks again for your contribution.

**Comment by drph4nt0m** [comment]
@kellyjandrews okie. Thanks a lot!

**Review by kellyjandrews — APPROVED** [review]
Thanks for this - much appreciated!

**Comment by marcschroeder** [comment]
Hey @kellyjandrews I have provided a PR to revert this change as it does not look like the default settings still work. Maybe you could have a look at it? Do the default setting (Not overriding anything) still work for you?
We had to build a new version of the library for our project today to get it to work.

**Comment by kellyjandrews** [comment]
Terribly sorry @marcschroeder - all of the tests were passing, so I must have missed it. I will double check and get this fixed today.

**Comment by marcschroeder** [comment]
Don't worry :) Worked perfectly for us with the small fix in place. Thanks for having a look at it! Let me know if you need something.

**Comment by kellyjandrews** [comment]
@marcschroeder looking at it right now - there was no test for the defaults - which is on me for not checking. I'll get this one  fixed up shortly.

**Comment by kellyjandrews** [comment]
@marcschroeder - do you have an exact error output you can share with me - I want to double check what error you were seeing, as I haven't been able to reproduce any issues.

**Comment by marcschroeder** [comment]
Sure, it should be:

```
Error: getaddrinfo ENOTFOUND https://rest.nexmo.com
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (node:dns:67:26) {
  errno: -3008,
  code: 'ENOTFOUND',
  syscall: 'getaddrinfo',
  hostname: 'https://rest.nexmo.com'
}
```

This sample code produces the error on @vonage/server-sdk@2.10.3 for me:

```
const vonage = new Vonage({
	apiKey: NEXMO_API_KEY,
	apiSecret: NEXMO_API_SECRET,
});
vonage.message.search({}, (e: any) => console.log(e));
```

**Pull request merged**
