### PR TITLE
Add Conversations v0.1 Support

### PR DESCRIPTION
**Pull request by AlexLakatos**
- Added support for Conversation API v0.1
- Removed `nexmo.users.getConversations`

### CODE REVIEW

**Review by hummusonrails — COMMENTED** [review]
Am I reading this correctly that the primary change here is updating the URL path in the functions?

**Comment by AlexLakatos** [comment]
Yeah, it's a pass-through SDK. So changing the base URL is all that's needed. There's a minor removal of multiple API paths at the same time and removing the users.getConversations method.

**Review by hummusonrails — APPROVED** [review]
🚀 _(... but not yet 😁 )_

**Review by aghahuseynov — APPROVED** [review]

**Comment by kellyjandrews** [comment]
Does anyone know if any of these changes are still valid after seven months?

**Comment by dragonmantank** [comment]
There will be some changes when v0.3 drops here relatively soon. It's close to this v0.1, but some minor changes.

**Comment by lornajane** [comment]
I believe that these changes were rolled into the beta branch which contains a combined set of changes for conversation, messages, and .... something else. These should have been separate branches IMO, releasing one of the beta featuresets and not another may be tricky with the current setup. This PR is outdated I _think_.

**Comment by mheap** [comment]
This is a separate Conversations implementation using the new spec, not what is currently in the beta branch

**Pull request closed without merging**
