### PR TITLE
feat: added number typings

### LINKED ISSUE #363: Number Types
Create Typings for Number API

### PR DESCRIPTION
**Pull request by privateOmega**
Added typings for number methods

## Description

fixes #363 

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by kellyjandrews** [comment]
@privateOmega  Thanks for your submission - I'll get this reviewed soon.

**Review by kellyjandrews — APPROVED** [review]
These look great - I'll get them merged in.

**Comment by kellyjandrews** [comment]
If you don't mind - could you resolve the branch conflict prior to merging?

**Comment by privateOmega** [comment]
@kellyjandrews sure will do in a couple of hours

**Comment by kellyjandrews** [comment]
No rush - thanks for your help!

**Comment by privateOmega** [comment]
@kellyjandrews I have rebased the branch with master.

**Comment by kellyjandrews** [comment]
Thanks again! I'll get this merged in.

**Pull request merged**
