### PR TITLE
Count Content-Length in actual bytes

### PR DESCRIPTION
**Pull request by ferk6a**
Hello! I saw the issue #196 and immediately went to look into the code to figure out why it was happening. Found out it was an issue with UTF-8 data, so I fixed it using the [node documentation examples on how to use the `http` module](https://nodejs.org/docs/latest-v9.x/api/http.html#http_response_writehead_statuscode_statusmessage_headers):

```javascript
const body = 'hello world';
response.writeHead(200, {
  'Content-Length': Buffer.byteLength(body),
  'Content-Type': 'text/plain' });
```

Using `byteLength` rather than string `length` seems to fix the problem, since it was counting characters wrong for UTF-8 encoded data.

I can provide tests for this, but I don't know where exactly they would fit in since there are multiple places in the code where the change has been made.

### CODE REVIEW

**Comment by mheap** [comment]
@fer22f Thanks for this. It looks like we need a test adding for each updated instance, as we can't write a single test due to the code being duplicated.

Each test uses a mocked HTTPClient instance, so it should be reasonable straightforward to assert that the headers provided match what we're expecting (specifically `Content-Length`)

**Comment by ferk6a** [comment]
@mheap I added some UTF-8 tests, some a bit silly (I don't think anyone should use Unicode in URLs directly like that, punycode would probably be used instead), see if you like it :)

The ones in TalkResource are probably the most important.

**Comment by mheap** [comment]
Looks great to me. @AlexLakatos could we get a review?

**Review by AlexLakatos — APPROVED** [review]
Looks really great, thanks for the PR!

**Comment by AlexLakatos** [comment]
We're celebrating Hacktoberfest this month, don't forget to fill out the form if you want to get the Nextoberfest T-Shirt https://www.nexmo.com/blog/2018/10/09/join-nextoberfest-tis-the-season-to-be-hacking-dr/

**Pull request merged**
