### PR TITLE
Improved grammar in Readme.md

### LINKED ISSUE #223: Error in grammar in README.md
The line:
`the option exist to process `
should instead be`the option exists to process `

### PR DESCRIPTION
**Pull request by Soundug**
Fixed #223

### CODE REVIEW

**Comment by AlexLakatos** [comment]
Thanks for the PR!

**Comment by Soundug** [comment]
Hi!
I contributed to Nexmo repo during hacktoberfest.
But I haven't heard about the t-shirt redemption mail yet.
Thanks!

Regards,
Soundarya.

**Comment by Soundug** [comment]
Hi!
I contributed to Nexmo repo during hacktoberfest.
But I haven't heard about the t-shirt redemption mail yet.
Thanks!

Regards,
Soundarya.


2018年10月25日(木) 15:06、Alex Lakatos さん（notifications@github.com）のメッセージ:

**Comment by AlexLakatos** [comment]
Hi,
The emails are going out this week, with the T-Shirts shipping in the next 10 days.

**Comment by Soundug** [comment]
Hi @AlexLakatos! Was just curious :) 
Thanks.

**Pull request merged**
