### PR TITLE
Escape app name in request

### LINKED ISSUE #50: createApplication does not like spaces in the name
``` js
> nexmo.createApplication('FooBar 1', 'voice', 'http://example.com/', 'http://example.com', {}, function(err, res) { console.log(err); console.log(res) });
TypeError: Request path contains unescaped characters
    at new ClientRequest (_http_client.js:53:11)
    at Object.exports.request (http.js:31:10)
    at Object.exports.request (https.js:199:15)
    at sendRequest (/Users/cbetta/code/nexmo/nexmo-cli/node_modules/easynexmo/lib/nexmo.js:228:27)
    at Object.exports.createApplication (/Users/cbetta/code/nexmo/nexmo-cli/node_modules/easynexmo/lib/nexmo.js:407:7)
    at repl:1:7
    at REPLServer.defaultEval (repl.js:272:27)
    at bound (domain.js:280:14)
    at REPLServer.runBound [as eval] (domain.js:293:12)
    at REPLServer.<anonymous> (repl.js:441:10)

```

### PR DESCRIPTION
**Pull request by cbetta**
Closes #50

### CODE REVIEW

**Comment by cbetta** [comment]
@pvela I'd love if you could merge and release this fix.

**Comment by pvela** [comment]
Should we use encodeURIComponent instead of encodeURI? I use encodeURIComponent in other places for encoding other parameters.

**Comment by cbetta** [comment]
I'm not sure. What is the diff?

**Comment by pvela** [comment]
If I remember correctly URIComponent encodes all special characters instead of just the spaces, for example if the name contains / or # it needs to be escaped as well which encodeURI doesn't.

**Comment by cbetta** [comment]
@pvela changed

**Comment by pvela** [comment]
thanks

**Pull request merged**
